apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sample-api
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
          - env: staging
          - env: prod
  template:
    metadata:
      name: 'sample-api-{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/SiliasOdion809/Project-Forge.git
        targetRevision: main
        path: 'live/addons/apps/sample-api/k8s/overlays/{{env}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true