apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-api
  labels:
    app: sample-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-api
  template:
    metadata:
      labels:
        app: sample-api
    spec:
      containers:
        - name: sample-api
          image: 791316000644.dkr.ecr.us-east-1.amazonaws.com/project-forge/sample-api:v0.1.1
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: "base"
            - name: APP_VERSION
              value: "0.1.1"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20